server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/jobgate_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.application.name=jobgate-backend
# JWT Configuration
jwt.secret=jobgate_secret_key_2024_very_long_and_secure_key_for_hmac_sha256
jwt.expiration=86400000